#!/bin/bash --norc

if [ "$LOGNAME" != "root" ]; then
    echo "You need to run $0 through sudo"
    exit 1
fi

if [ -x /usr/sbin/daemonize ]; then
    DAEMONIZE=/usr/sbin/daemonize
elif [ -x /usr/bin/daemonize ]; then
    DAEMONIZE=/usr/bin/daemonize
else
    echo "Cannot execute daemonize to start systemd."
    exit 1
fi

if ! command -v /lib/systemd/systemd > /dev/null; then
    echo "Cannot execute /lib/systemd/systemd."
    exit 1
fi

if ! command -v /usr/bin/unshare > /dev/null; then
    echo "Cannot execute /usr/bin/unshare."
    exit 1
fi

SYSTEMD_EXE="/lib/systemd/systemd --system-unit=basic.target"
SYSTEMD_PID="$(ps -eo pid=,args= | awk '$2" "$3=="'"$SYSTEMD_EXE"'" {print $1}')"
if [ -z "$SYSTEMD_PID" ]; then
    echo -e "WSL_INTEROP=$WSL_INTEROP\nWSL_DISTRO_NAME=$WSL_DISTRO_NAME\nWSLENV=$WSLENV\nWT_PROFILE_ID=$WT_PROFILE_ID\nWT_SESSION=$WT_SESSION\nWAYLAND_DISPLAY=$WAYLAND_DISPLAY\nDISPLAY=$DISPLAY\nXDG_RUNTIME_DIR=$XDG_RUNTIME_DIR\nPULSE_SERVER=$PULSE_SERVER" > /run/WSL/systemd.env
    echo -e "WSL_INTEROP=$WSL_INTEROP\nWSL_DISTRO_NAME=$WSL_DISTRO_NAME\nWSLENV=$WSLENV\nWT_PROFILE_ID=$WT_PROFILE_ID\nWT_SESSION=$WT_SESSION\nWAYLAND_DISPLAY=$WAYLAND_DISPLAY\nXDG_RUNTIME_DIR=$XDG_RUNTIME_DIR\nPULSE_SERVER=$PULSE_SERVER" > /run/WSL/systemd.bashrc
    "$DAEMONIZE" /usr/bin/unshare --fork --pid --mount-proc bash -c 'export container=wsl; exec '"$SYSTEMD_EXE"
    while [ -z "$SYSTEMD_PID" ]; do
        echo "Sleeping for 1 second to let systemd settle"
        sleep 1
        SYSTEMD_PID="$(ps -eo pid=,args= | awk '$2" "$3=="'"$SYSTEMD_EXE"'" {print $1}')"
    done
fi

USER_HOME="$(getent passwd | awk -F: '$1=="'"$SUDO_USER"'" {print $6}')"
if [ -n "$SYSTEMD_PID" ] && [ "$SYSTEMD_PID" != "1" ]; then
    if [ -n "$1" ] && [ "$1" != "bash --login" ] && [ "$1" != "/bin/bash --login" ]; then
        exec /usr/bin/nsenter -t "$SYSTEMD_PID" -m -p \
            /usr/bin/sudo -H -u "$SUDO_USER" \
            /bin/bash -c 'set -a; [ -f "$HOME/.systemd-env" ] && source "$HOME/.systemd-env"; set +a; exec bash -c '"$(printf "%q" "$@")"
    else
        exec /usr/bin/nsenter -t "$SYSTEMD_PID" -m -p \
            /bin/login -p -f "$SUDO_USER" \
            $([ -f "$USER_HOME/.systemd-env" ] && /bin/cat "$USER_HOME/.systemd-env" | xargs printf ' %q')
    fi
    echo "Existential crisis"
    exit 1
fi
